language: java
sudo: false
after_success:
- bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  api_key:
    secure: dgbYUK85ONuVhdHJOlaAkp8u9GS9RGHsylTwdIYIKAYyLaQW7cGADC9YADZ1R7v0mKXP3xRODpBKTZQvEgt2HlQRj3RV9KpFw1WTmPN/pD+aRPa3ry8giJ7PwKrQADtK1ss5YgcUagJlK9iEMo1IZFr2e/kt1qX5XPJgGDldvLsvyRj0+U+DbfBNKFaQXmO9fllW7wUx4neJXAMNckYZplm9G7yI12PckMt1tPMMZcIOlKL/q37na3Q+eM1+XJU/Q4G7Iof2jSSomjmHE6seOfzk2tMl+HK+6U4+C/U201wZknAMEATy5mvL3KhwdaGrDd3Oy/l4fLX4pQVG40PU5yWcHEITilA9R0yNR6ZjFs1PT5cUHd1RsyC1cJXfsYXV/YM4m1JiuVwNJQIPtIPZX0kCXzb0NhJb3zdEAcf/VupFA3vU4gejAUSx9G9Mf23+yq2RG6JuLhEsuxVg4tqV+B/RdmcsK58R3znGIKHeBuIpMjlyMCXu+gjhL1p5w4OOwmythJT4OUDvpTgeV/G86aK4Oy4I+pnyPPXgwjn0zPHvvMK/lhJ5naocNo+LgUQm3DhyyNbkqFNwFoiVXH0OAWtiHbHD7PpZ4SvbJK0jcSwCAIUUBGBTwz7Xxev20oUa2Y8woJDCRbn/0uRoVDx3kahJMFTJ7RFXfs6i9Tild7k=
  file: WeatherSwingViewer-1.0-full.jar
  on:
    repo: WeDism/WeatherSwingViewer
addons:
  apt:
    packages:
    - xvfb
install:
- export DISPLAY=':99.0'
- Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
notifications:
  email:
    recipients:
    - wedinakawer58@gmail.com
    on_success: never
    on_failure: always
