package com.weather_viewer.gui.previews.start;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.weather_viewer.gui.general.General;

import javax.swing.*;
import java.awt.*;

public class StartPreview extends JFrame {
    private JPanel rootPanel;
    private JLabel gifLabel;

    public StartPreview() {
        setLocationRelativeTo(null);
        getContentPane().add(rootPanel);
        setUndecorated(true);

        setBackground(new Color(0, 0, 0, 0));
        setIconImage(new ImageIcon(General.class.getResource("/images/PartlyCloudy.png")).getImage());

        pack();
        setResizable(false);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.setDoubleBuffered(true);
        rootPanel.setName("");
        rootPanel.setOpaque(false);
        rootPanel.setPreferredSize(new Dimension(256, 256));
        gifLabel = new JLabel();
        gifLabel.setDoubleBuffered(true);
        gifLabel.setIcon(new ImageIcon(getClass().getResource("/gifs/loading.gif")));
        gifLabel.setText("");
        rootPanel.add(gifLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
